# -*- coding: utf-8 -*-
"""Security2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kHZH0WnCKsN38j-hNABY1Ndt0qAnSzuz
"""

# =========================================
# 1. IMPORTS
# =========================================
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.feature_selection import VarianceThreshold
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.metrics import classification_report, confusion_matrix

from sklearn.utils import class_weight

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.regularizers import l2

import matplotlib.pyplot as plt
import joblib

# =========================================
# 2. LOAD DATA
# =========================================
df = pd.read_csv("/content/compressed_data.csv.gz")

print("Dataset Shape:", df.shape)
print(df[' Label'].value_counts())

# =========================================
# 3. REMOVE DATA LEAKAGE FEATURES
# =========================================
drop_cols = ['Flow Bytes/s', 'Flow Packets/s', 'Timestamp']

df = df.drop(columns=drop_cols, errors='ignore')

# =========================================
# 4. PREPROCESSING
# =========================================

# Binary label
df['target'] = df[' Label'].apply(lambda x: 0 if x == 'BENIGN' else 1)

# Multi-class label
le = LabelEncoder()
df['attack_type'] = le.fit_transform(df[' Label'])

# Features
X = df.drop([' Label', 'target', 'attack_type'], axis=1)

# Clean data
X = X.replace([np.inf, -np.inf], np.nan)
X = X.fillna(0)

y_binary = df['target']
y_multi = df['attack_type']

# =========================================
# 5. FEATURE SELECTION
# =========================================

print("\n=== Feature Selection ===")

# Variance Threshold
vt = VarianceThreshold(threshold=0.01)
X_var = vt.fit_transform(X)

# Correlation Removal
X_df = pd.DataFrame(X_var)

corr_matrix = X_df.corr().abs()
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))

to_drop = [col for col in upper.columns if any(upper[col] > 0.95)]
X_uncorr = X_df.drop(columns=to_drop)

# Feature Importance
rf_temp = RandomForestClassifier(n_estimators=100, random_state=42)
rf_temp.fit(X_uncorr, y_binary)

sfm = SelectFromModel(rf_temp, threshold="median")
X_selected = sfm.transform(X_uncorr)

print("Final Feature Shape:", X_selected.shape)

# =========================================
# 6. STRATIFIED SPLIT (NO LEAKAGE)
# =========================================

X_train, X_test, y_train_bin, y_test_bin = train_test_split(
    X_selected,
    y_binary,
    test_size=0.2,
    stratify=y_binary,
    random_state=42
)

_, _, y_train_multi, y_test_multi = train_test_split(
    X_selected,
    y_multi,
    test_size=0.2,
    stratify=y_multi,
    random_state=42
)

# =========================================
# 7. SCALING
# =========================================

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# =========================================
# 8. CROSS VALIDATION (REAL PERFORMANCE)
# =========================================

print("\n=== Cross Validation ===")

rf_check = RandomForestClassifier(n_estimators=100)
cv_scores = cross_val_score(rf_check, X_selected, y_binary, cv=5)

print("CV Accuracy:", cv_scores)
print("Mean CV Accuracy:", cv_scores.mean())

# =========================================
# 9. CLASS IMBALANCE HANDLING
# =========================================

weights = class_weight.compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train_bin),
    y=y_train_bin
)

class_weights = dict(enumerate(weights))

# =========================================
# 10. DEEP LEARNING (REGULARIZED)
# =========================================

print("\n=== Deep Learning: Binary ===")

model_bin = Sequential([
    Dense(64, activation='relu', kernel_regularizer=l2(0.001), input_shape=(X_train.shape[1],)),
    BatchNormalization(),
    Dropout(0.5),

    Dense(32, activation='relu', kernel_regularizer=l2(0.001)),
    Dropout(0.5),

    Dense(1, activation='sigmoid')
])

model_bin.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

early_stop = EarlyStopping(patience=3, restore_best_weights=True)

history = model_bin.fit(
    X_train, y_train_bin,
    validation_data=(X_test, y_test_bin),
    epochs=10,
    batch_size=256,
    class_weight=class_weights,
    callbacks=[early_stop]
)

# =========================================
# 11. EVALUATION (BINARY)
# =========================================

y_pred_bin = (model_bin.predict(X_test) > 0.5).astype(int)

print("\nBinary Classification Report:")
print(classification_report(y_test_bin, y_pred_bin))

print("Confusion Matrix:")
print(confusion_matrix(y_test_bin, y_pred_bin))

# =========================================
# 12. MULTI-CLASS MODEL (REGULARIZED)
# =========================================

print("\n=== Deep Learning: Multi-Class ===")

y_train_multi_cat = tf.keras.utils.to_categorical(y_train_multi)
y_test_multi_cat = tf.keras.utils.to_categorical(y_test_multi)

model_multi = Sequential([
    Dense(64, activation='relu', kernel_regularizer=l2(0.001), input_shape=(X_train.shape[1],)),
    BatchNormalization(),
    Dropout(0.5),

    Dense(32, activation='relu'),
    Dropout(0.5),

    Dense(y_train_multi_cat.shape[1], activation='softmax')
])

model_multi.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model_multi.fit(
    X_train, y_train_multi_cat,
    validation_data=(X_test, y_test_multi_cat),
    epochs=10,
    batch_size=256,
    callbacks=[early_stop]
)

# =========================================
# 13. EVALUATION (MULTI-CLASS)
# =========================================

y_pred_multi = model_multi.predict(X_test)
y_pred_classes = np.argmax(y_pred_multi, axis=1)

print("\nMulti-Class Classification Report:")
print(classification_report(y_test_multi, y_pred_classes))

# =========================================
# 14. OVERFITTING CHECK (PLOT)
# =========================================

plt.plot(history.history['accuracy'], label='train_acc')
plt.plot(history.history['val_accuracy'], label='val_acc')
plt.legend()
plt.title("Overfitting Check")
plt.show()

# =========================================
# 15. SAVE MODELS
# =========================================

model_bin.save("dl_binary_model.h5")
model_multi.save("dl_multi_model.h5")

joblib.dump(scaler, "scaler.pkl")
joblib.dump(le, "label_encoder.pkl")

print("\n✅ Models saved successfully!")