async function sendEmail(data) {
  try {
    const message = `
🚨 INTRUSION DETECTED 🚨

━━━━━━━━━━━━━━━━━━━━━━━
⚠️ Alert Details
━━━━━━━━━━━━━━━━━━━━━━━

🧠 Status       : ${data.anomaly ? "ANOMALY DETECTED" : "NORMAL"}
🎯 Attack Type  : ${data.attackType || "Unknown"}
⏰ Time         : ${new Date().toLocaleString()}

━━━━━━━━━━━━━━━━━━━━━━━
📊 System Info
━━━━━━━━━━━━━━━━━━━━━━━

This alert was generated by the IDS system after analyzing incoming network traffic using a machine learning model.

━━━━━━━━━━━━━━━━━━━━━━━
🔒 Action Recommended
━━━━━━━━━━━━━━━━━━━━━━━

• Investigate suspicious traffic
• Check server logs
• Monitor for repeated activity

━━━━━━━━━━━━━━━━━━━━━━━
⚡ IDS Cyber Defense System
━━━━━━━━━━━━━━━━━━━━━━━
`;

    await transporter.sendMail({
      from: `"IDS Security System" <${process.env.EMAIL}>`,
      to: process.env.RECEIVER_EMAIL,
      subject: `🚨 [ALERT] ${data.attackType || "Suspicious Activity Detected"}`,
      text: message,
    });

    console.log("📧 Email sent");
  } catch (err) {
    console.error("Email error:", err.message);
  }
}